### ISSUE TITLE
Cannot find module 'ngx-countdown-timer' or its corresponding type declarations.

### ISSUE THREAD

**Issue by barart** [markpenaranda/ngx-countdown-timer#26]
I upgraded from v 0.1.9 to 0.2.0 and i got this error: Cannot find module 'ngx-countdown-timer' or its corresponding type declarations. I dont know why if it was working fine on 0.1.9, is ther any not documented change or something else i need to do?
